# RPC
rpc-http-enabled=true
graphql-http-enabled=true
rpc-ws-enabled=true

rpc-http-port=4545
graphql-http-port=4547
rpc-ws-port=4546

rpc-http-api=["ADMIN","ETH","NET","WEB3","QBFT","TXPOOL","PERM","TRACE"]
rpc-ws-api=["ADMIN","ETH","NET","WEB3","QBFT","TXPOOL","PERM","TRACE"]
## Uncomment the following lines to allow RPC from remote locations (risky)
host-allowlist=["*"]
rpc-http-host="0.0.0.0"
rpc-ws-host="0.0.0.0"
rpc-http-cors-origins=["*"]
graphql-http-host="0.0.0.0"

engine-rpc-enabled=false
engine-rpc-port=0

# Desactiva discovery si solo usas static-nodes
#discovery-enabled=false

# Networking
p2p-host="127.0.0.1"
p2p-port=60606
sync-min-peers=0
# Gas
min-gas-price=0

revert-reason-enabled=true
node-private-key-file="./keys/key"

